#格式很重要
spring:
  profiles:
    active: dev
  datasource:
     driver-class-name: com.mysql.jdbc.Driver

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/*.xml
    configLocation: classpath:mybatis.xml