spring:
    datasource:
       url: jdbc:mysql://127.0.0.1:3306/springbootmybatis?characterEncoding=utf8
       #
       username: root
       password: root
        #连接池的配置信息
       initialSize: 10
       minIdle: 10
       maxActive: 100
       maxWait: 60000
       timeBetweenEvictionRunsMillis: 60000
       minEvictableIdleTimeMillis: 300000
       validationQuery: SELECT 1 FROM DUAL
       testWhileIdle: true
       testOnBorrow: false
       testOnReturn: false
       poolPreparedStatements: true
       maxPoolPreparedStatementPerConnectionSize: 20

server:
  port: 8080
#  context-path: /hh #项目前加hh访问

#默认用户名密码
login:
  name: admin
  pass: 123456

#
#cupSize: B
#age: 19
#content: "cupSize:${cupSize},age:${age}"
girl:
  cupSize: B
  age: 19
